simple = (5, 6)
two = ((5, 6), (6, 5))
three = (((5, 6), (5, 4)), ((6, 7), (6, 5)))

print(simple)
print(simple[0])
print()
print(two)
print(two[0])
print(two[0][0])
print()
print(three)
print(three[0])
print(three[0][0])
print(three[0][0][0])